### ISSUE TITLE
Several Issues Question

### ISSUE THREAD

**Issue by hesingh** [Azure/sonic-sairedis#422]
1. The README.md file uses '-t trusty'.  Is the trusty for the Ubuntu version?  
    If so, I am using Ubuntu 18.04 and installed any software using '-t trusty' without it.  Is that correct?
2.  The README.md says "Get SAI header files into /usr/include/sai."  Where does one get the SAI header files from?  I don't have an asic/switch, what do I do to run sairedis DB on a Ubuntu machine?  I haven't invoked this "Get SAI header files" step.

I used 'autogen.sh' followed by './configure' and 'make'.  make fails as shown below.

```
hemant@ubuntu:~/sonic-sairedis$ make
make  all-recursive
make[1]: Entering directory '/home/hemant/sonic-sairedis'
Making all in meta
make[2]: Entering directory '/home/hemant/sonic-sairedis/meta'
make -C ../SAI/meta
make[3]: Entering directory '/home/hemant/sonic-sairedis/SAI/meta'
Makefile:68: *** "Missing doxygen in PATH".  Stop.
make[3]: Leaving directory '/home/hemant/sonic-sairedis/SAI/meta'
Makefile:1265: recipe for target '../SAI/meta/saimetadata.c' failed
make[2]: *** [../SAI/meta/saimetadata.c] Error 2
make[2]: Leaving directory '/home/hemant/sonic-sairedis/meta'
Makefile:404: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/hemant/sonic-sairedis'
Makefile:336: recipe for target 'all' failed
make: *** [all] Error 2
hemant@ubuntu:~/sonic-sairedis$ hemant@ubuntu:~/sonic-sairedis$ make
make  all-recursive
make[1]: Entering directory '/home/hemant/sonic-sairedis'
Making all in meta
make[2]: Entering directory '/home/hemant/sonic-sairedis/meta'
make -C ../SAI/meta
make[3]: Entering directory '/home/hemant/sonic-sairedis/SAI/meta'
Makefile:68: *** "Missing dot in PATH".  Stop.
make[3]: Leaving directory '/home/hemant/sonic-sairedis/SAI/meta'
Makefile:1265: recipe for target '../SAI/meta/saimetadata.c' failed
make[2]: *** [../SAI/meta/saimetadata.c] Error 2
make[2]: Leaving directory '/home/hemant/sonic-sairedis/meta'
Makefile:404: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/hemant/sonic-sairedis'
Makefile:336: recipe for target 'all' failed
make: *** [all] Error 2
hemant@ubuntu:~/sonic-sairedis$ 
```

**Comment by hesingh** [comment]
I installed SAI:
```
git clone --recursive https://github.com/opencomputeproject/SAI
```
Now the 'make' for sairedis has one less error:

```
hemant@ubuntu:~/sonic-sairedis$ make
make  all-recursive
make[1]: Entering directory '/home/hemant/sonic-sairedis'
Making all in meta
make[2]: Entering directory '/home/hemant/sonic-sairedis/meta'
make -C ../SAI/meta
make[3]: Entering directory '/home/hemant/sonic-sairedis/SAI/meta'
Makefile:68: *** "Missing dot in PATH".  Stop.
make[3]: Leaving directory '/home/hemant/sonic-sairedis/SAI/meta'
Makefile:1265: recipe for target '../SAI/meta/saimetadata.c' failed
make[2]: *** [../SAI/meta/saimetadata.c] Error 2
make[2]: Leaving directory '/home/hemant/sonic-sairedis/meta'
Makefile:404: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/hemant/sonic-sairedis'
Makefile:336: recipe for target 'all' failed
make: *** [all] Error 2
hemant@ubuntu:~/sonic-sairedis$
```

**Comment by hesingh** [comment]
1. Fixed missing 'dot' by installing graphviz.  
2. Then I fixed perl @INC issue for utils.pm not found
3.  Installed swss-common and puts is common/*.h in /usr/include/swss, changed 'long long' to int64_t in redisselect.cpp.
4.  I had to change some code to reach linking stage which fails: ```/usr/bin/ld: cannot find -lsai```

See diffs below.
```
diff --git a/meta/sai_serialize.h b/meta/sai_serialize.h
index daa9079..e0397e0 100644
--- a/meta/sai_serialize.h
+++ b/meta/sai_serialize.h
@@ -14,7 +14,7 @@ extern "C" {
 #include <map>
 #include <tuple>
 #include <string.h>
-#include "swss/logger.h"
+#include "/usr/include/swss/logger.h"
 #include "sai_meta.h"
 
 // util
diff --git a/meta/saiattributelist.h b/meta/saiattributelist.h
index 8c3a7c9..1a446dd 100644
--- a/meta/saiattributelist.h
+++ b/meta/saiattributelist.h
@@ -6,9 +6,9 @@
 #include <unordered_map>
 
 #include <hiredis/hiredis.h>
-#include "swss/dbconnector.h"
-#include "swss/table.h"
-#include "swss/logger.h"
+#include "/usr/include/swss/dbconnector.h"
+#include "/usr/include/swss/table.h"
+#include "/usr/include/swss/logger.h"
 #include "sai.h"
 #include "sai_serialize.h"
 #include "string.h"
diff --git a/syncd/syncd_applyview.cpp b/syncd/syncd_applyview.cpp
index 1c16efd..729e3fd 100644
--- a/syncd/syncd_applyview.cpp
+++ b/syncd/syncd_applyview.cpp
@@ -2615,7 +2615,7 @@ std::shared_ptr<SaiObj> findCurrentBestMatchForNextHopGroup(
         SWSS_LOG_NOTICE("failed to find route candidate for NHG: %s",
                 temporaryObj->str_object_id.c_str());
 
-        return false;
+        return nullptr;
     }
 
     /*
diff --git a/syncd/syncd_notifications.cpp b/syncd/syncd_notifications.cpp
index 2b53828..01524c5 100644
--- a/syncd/syncd_notifications.cpp
+++ b/syncd/syncd_notifications.cpp
@@ -532,7 +532,7 @@ bool ntf_queue_t::enqueue(
         return true;
     }
 
-    static uint32_t log_count = 0;
+    static uint64_t log_count = 0;
 
     if (!(log_count % 1000))
     {
@@ -782,6 +782,6 @@ void check_notifications_pointers(
          * Here we translated pointer, just log it.
          */
 
-        SWSS_LOG_INFO("%s: %lp (orch) => %lp (syncd)", meta->attridname, prev, attr.value.ptr);
+        SWSS_LOG_INFO("%s: %p (orch) => %p (syncd)", meta->attridname, prev, attr.value.ptr);
     }
 }
```

**Comment by kcudnik** [comment]
obsoleted, please reopen if issue still exists on current code
